name: flutter_getx_the_moviedb
description: Flutter TheMovieDB Application with GetX State, Route & Dependency Managements

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  connectivity_plus: ^2.2.0
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.4

  #flutter
  flutter:
    sdk: flutter
  flutter_i18n: ^0.31.1
  flutter_svg: ^1.0.3

  #getx
  get: ^4.6.1
  get_storage: ^2.0.3

  google_fonts: ^2.2.0
  nil: ^1.1.1
  responsive_framework: ^0.1.5
  url_launcher: ^6.0.18
  video_player: ^2.2.18

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.0.1+1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path_android: assets/icons/app_icon.png
  ios: true
  image_path_ios: assets/icons/app_icon.png

flutter:
  assets:
    - assets/
    - assets/flutter_i18n/
    - assets/icons/

  uses-material-design: true