name: flutter_getx_the_moviedb
description: A new Flutter TheMovieDB Application with GetX State Management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  connectivity: ^3.0.6
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.3
  device_preview: ^0.7.4
  dio: ^4.0.0

  #Flutter
  flutter:
    sdk: flutter
  flutter_i18n: ^0.30.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.1
  flutter_svg: ^0.22.0

  #GetX
  get: ^4.3.8
  get_storage: ^2.0.3

  google_fonts: ^2.1.0
  url_launcher: ^6.0.3
  video_player: ^2.1.15

  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path_android: assets/icons/app_icon.png
  ios: true
  image_path_ios: assets/icons/app_icon.png


flutter_native_splash:
  image: assets/icons/app_icon.png
  color: "#000000"


flutter:
  assets:
    - assets/flutter_i18n/
    - assets/icons/

  uses-material-design: true