name: flutter_getx_the_moviedb
description: Flutter TheMovieDB Application with GetX State Management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.4
  device_preview: ^1.0.0

  #Flutter
  flutter:
    sdk: flutter
  flutter_i18n: ^0.31.0
  flutter_launcher_icons: ^0.9.2
  flutter_screenutil: ^5.0.1
  flutter_svg: ^1.0.0

  #GetX
  get: ^4.5.1
  get_storage: ^2.0.3

  google_fonts: ^2.1.0
  url_launcher: ^6.0.17
  video_player: ^2.2.7

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path_android: assets/icons/app_icon.png
  ios: true
  image_path_ios: assets/icons/app_icon.png

flutter:
  assets:
    - assets/icons/

  uses-material-design: true