name: flutter_getx_the_moviedb
description: Flutter TheMovieDB Application with GetX State, Route & Dependency Managements

module:
  androidPackage: com.islerdestek.mobile
  iosBundleIdentifier: com.islerdestek.mobile

publish_to: 'none'

version: 1.0.0+1

environment:
  flutter: "3.0.5"
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  another_flushbar: ^1.10.29
  connectivity_plus: ^2.3.6
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  dropdown_search: ^5.0.2
  equatable: ^2.0.3

  #flutter
  flutter:
    sdk: flutter
  flutter_i18n: ^0.32.4
  flutter_svg: ^1.1.1+1

  #getx
  get: ^4.6.5
  get_storage: ^2.0.3

  google_fonts: ^3.0.1
  nil: ^1.1.1
  responsive_framework: ^0.2.0
  url_launcher: ^6.1.5
  url_strategy: ^0.2.0
  video_player: ^2.4.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.6
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path_android: assets/icons/app_icon.png
  ios: true
  image_path_ios: assets/icons/app_icon.png

flutter:
  assets:
    - assets/
    - assets/flutter_i18n/
    - assets/icons/

  uses-material-design: true